In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([4,5,6])

In [4]:
a

array([1, 2, 3])

In [5]:
a + b

array([5, 7, 9])

In [6]:
a * b

array([ 4, 10, 18])

In [7]:
a ** 3

array([ 1,  8, 27])

In [13]:
np.complex64(a)

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [8]:
a - b

array([-3, -3, -3])

In [4]:
np.sum(a)

np.int64(6)

In [5]:
np.mean(a)

np.float64(2.0)

In [6]:
np.max(a)

np.int64(3)

In [9]:
np.sum(b,axis=0)

array([12, 15, 18])

In [10]:
np.sum(b,axis=1)

array([ 6, 15, 24])

In [24]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.var(a)

np.float64(0.6666666666666666)

In [28]:
b*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [29]:
d = np.array([1,'a',2])

In [30]:
d

array(['1', 'a', '2'], dtype='<U21')

In [35]:
e = np.array([1,'baa',3,4])

In [39]:
b**5

array([[    1,    32,   243],
       [ 1024,  3125,  7776],
       [16807, 32768, 59049]])

In [40]:
a

array([1, 2, 3])

In [41]:
a.shape

(3,)

In [42]:
a.ndim

1

In [43]:
a.size

3

In [44]:
c.shape

(3, 3)